source 'https://rubygems.org'

gem 'base64'
gem 'bcrypt'
gem 'bigdecimal'
gem 'bindata'
gem 'file-tail'
gem 'geocoder'
gem 'inifile'
gem 'oj'
gem 'openssl', '~> 3.2'
gem 'pry'
gem 'sinatra'
gem 'sys-proctable'
gem 'sysrandom'
gem 'toml-rb'
gem 'unicode-display_width'
gem 'rubyzip', '~> 2.3.0'


gem "webrick", "~> 1.7"
